### ISSUE TITLE
KGiSL Institute of Technology

### ISSUE THREAD

**Issue by sriram23** [MozillaTN/clubs#1]
- College Name : KGiSL Institute of Technology, Saravanampatti, Coimbatore.
 - Contributor telegram handle : @SriramB (https://t.me/SriramB)
 - what name should your repo be : KiTE
    
    ( Say we have mozillatn.github.io/clubs for random college in page of clubs what should come for you )
 - Can you spend one hour for 5 days to create website : Yes

**Comment by iamVP7** [comment]
Repo created https://github.com/MozillaTN/KiTE

**Comment by iamVP7** [comment]
@sriram23  shall we close the issue, as you are maintaining the website actively ?
