### ISSUE TITLE
Vellore Institute of Technology, Vellore

### ISSUE THREAD

**Issue by itsN1X** [MozillaTN/clubs#12]
- College Name : Vellore Institute of Technology, Vellore
 - Contributor telegram handle : @itsN1X
 - what name should your repo be : VIT
 - Can you spend one hour for 5 days to create website : YES

**Comment by iamVP7** [comment]
Ping @iamvp7 in telegram

**Comment by itsN1X** [comment]
No #IRC chans?

**Comment by iamVP7** [comment]
Sorry as of now not active in IRC

**Comment by iamVP7** [comment]
Repo created. https://github.com/MozillaTN/VIT did you join telegram group..

**Comment by itsN1X** [comment]
Yeah, thanks, I'm on the website group. @iamVP7

**Comment by iamVP7** [comment]
Once from ur College any one conduct test days and push report this comment has to b closed

**Comment by itsN1X** [comment]
Wen next test @iamVP7 ?
