### ISSUE TITLE
DHIRAJLAL GANDHI COLLEGE OF TECHNOLOGY, SALEM

### ISSUE THREAD

**Issue by Dhevendhirancs** [MozillaTN/clubs#16]
- College Name : Dhirajlal Gandhi College of Technolgy, Salem
 - Contributor telegram handle : dhevendhiran_m
 - what name should your repo be : Dhirajzilla
    
    ( Say we have mozillatn.github.io/clubs for random college in page of clubs what should come for you )
 - Can you spend one hour for 5 days to create website : Yes

**Comment by iamVP7** [comment]
Should name you ur website be mozillaTN.github.io/Dhirajzilla or it can be anything different

**Comment by Dhevendhirancs** [comment]
yeah its ok anna
Dhirajzilla is good for ur website

**Comment by iamVP7** [comment]
Hey @Dhevendhirancs  created repo for your college https://github.com/MozillaTN/Dhirajzilla lets work there.

**Comment by iamVP7** [comment]
Website for [CC-Dhirajzilla](https://mozillatn.github.io/Dhirajzilla) is created. 
Thanks @Dhevendhirancs   for building amazing website for your college. Hope you can update in upcoming days.
