### ISSUE TITLE
SRM University,Ramapuram

### ISSUE THREAD

**Issue by Balaji2198** [MozillaTN/clubs#23]
### Issue name should be your college full name. For example    KIOT - Knowledge Institute of Technology, Salem

Did you check whether you college name exist in issue : yes. It's not there.
 - College Name : SRM University, Ramapuram
 - Contributor telegram handle : @balaji2198
 - what name should your repo be : SRMozilla
    
    ( Say we have mozillatn.github.io/clubs for random college in page of clubs what should come for you )
 - Can you spend one hour for 5 days to create website : yes

**Comment by iamVP7** [comment]
Is website published.

**Comment by Balaji2198** [comment]
Yes , This is the Website link [srmozilla](https://mozillatn.github.io/srmozilla/)
