### ISSUE TITLE
AIT - Army Institute of Technology, Pune

### ISSUE THREAD

**Issue by shraddhanayak07** [MozillaTN/clubs#24]
### Issue name should be your college full name. For example    KIOT - Knowledge Institute odf Technology, Salem
Did you check whether you college name exisit in issue : yes. Not Exists
 - College Name : Army Institute of Technology
 - Contributor telegram handle : @shradds07
 - what name should your repo be : MozillAITs
    
    ( Say we have mozillatn.github.io/clubs for random college in page of clubs what should come for you )
 - Can you spend one hour for 5 days to create website :yes

**Comment by iamVP7** [comment]
@shraddhanayak07 as of now we are limiting inside Tamilnadu. Hope will open access soon to others. So closing the issue now
