### ISSUE TITLE
SAVEETHA ENGINEERING COLLEGE

### ISSUE THREAD

**Issue by pavangudiwada** [MozillaTN/clubs#27]
### Issue name :    SAVEETHA ENGINEERING COLLEGE
Did you check whether you college name exisit in issue : yes 
 - College Name :SAVEETHA ENGINEERNG COLLEGE
 - Contributor telegram handle :@pavangudiwada 
 - what name should your repo be :SECclub
 - Can you spend one hour for 5 days to create website : yes

**Comment by iamVP7** [comment]
Lets work on the weekend.

**Comment by pavangudiwada** [comment]
ok..

**Comment by pavangudiwada** [comment]
This is no longer needed.
