### ISSUE TITLE
KCG COLLEGE OF TECHNOLOGY

### ISSUE THREAD

**Issue by VishVishaal** [MozillaTN/clubs#3]
College Name : KCG COLLEGE OF TECHNOLOGY
Contributor telegram handle : @VishVishaal
what name should your repo be : Mozilla@KCG
Can you spend one hour for 5 days to create website : Yes

**Comment by iamVP7** [comment]
Website URL can't have special characters.. so will have KCG ?

**Comment by iamVP7** [comment]
Duplicate #20
