### ISSUE TITLE
SNS College of Technology

### ISSUE THREAD

**Issue by surentharan** [MozillaTN/clubs#4]
### Issue name should be your college full name. For example    KIOT - Knowledge Institute odf Technology, Salem
Did you check whether you college name exisit in issue : yes
 - College Name : SNS College of Technology
 - Contributor telegram handle :@surenvino
 - what name should your repo be :snsct
    
    ( Say we have mozillatn.github.io/clubs for random college in page of clubs what should come for you )
 - Can you spend one hour for 5 days to create website : Yes

**Comment by iamVP7** [comment]
Repo crated https://github.com/MozillaTN/snsct

**Comment by iamVP7** [comment]
Website for [CC-SNSCT](https://mozillatn.github.io/snsct/) is created. 
Thanks @surentharan  for building amazing website for your college. Hope you can update in upcoming days.
