### ISSUE TITLE
Sri Krishna College of Engineering and Technology

### ISSUE THREAD

**Issue by lokeshwaran97** [MozillaTN/clubs#9]
### Issue name should be your college full name. For example    KIOT - Knowledge Institute odf Technology, Salem
Did you check whether you college name exisit in issue : yes / no
 - College Name :Sri Krishna College of Engineering and technology
 - Contributor telegram handle :@Lokeshwaran97
 - what name should your repo be :SKCETzilla
    
    ( Say we have mozillatn.github.io/clubs for random college in page of clubs what should come for you )
 - Can you spend one hour for 5 days to create website :

**Comment by iamVP7** [comment]
Hey do you need zilla at end or is it enough to have SKCET

**Comment by lokeshwaran97** [comment]
That's OK na
